#!/usr/bin/env python3
"""Generate long treadmilling-only nuclear-aster pilot configs."""

from __future__ import annotations

import csv
from pathlib import Path
from textwrap import dedent


ROOT = Path(__file__).resolve().parent
PRODUCTION = ROOT / "production"
SMOKE = ROOT / "00_smoke_parse"

TIME_STEP = 0.005
RUN_STEPS = 60000  # 5 min at dt = 0.005 s
RUN_FRAMES = 300   # one saved frame per second
SMOKE_STEPS = 400
SMOKE_FRAMES = 8
REPLICATES = 3

BOX_LENGTH = (32.0, 16.0, 2.0)
NUCLEUS_START = (0.0, 0.0, 0.0)
NUCLEUS_RADIUS = 0.5
FIBER_COUNT = 120
INITIAL_LENGTH = 0.1
MAX_LENGTH = 1.0
TOTAL_POLYMER = 12000
CAP_ANGLE_RAD = 0.95  # ~54 degrees around the chosen nucleus side

CASES = [
    {
        "name": "01_symmetric_dense_treadmill",
        "description": "Symmetric dense nucleus-bound actin aster with treadmilling-only turnover.",
        "aster": "symmetric",
        "direction": "",
        "nucleator": True,
    },
    {
        "name": "02_minus_x_cap_dense_treadmill",
        "description": "Dense one-sided minus-x cap aster with treadmilling-only turnover.",
        "aster": "cap",
        "direction": "-1 0 0",
        "nucleator": True,
    },
    {
        "name": "03_plus_x_cap_dense_treadmill",
        "description": "Dense one-sided plus-x cap aster; direction-flip control.",
        "aster": "cap",
        "direction": "1 0 0",
        "nucleator": True,
    },
    {
        "name": "04_no_nucleator_control",
        "description": "Nucleus body without actin nucleation; passive drift baseline.",
        "aster": "none",
        "direction": "",
        "nucleator": False,
    },
]


def fmt_pos(pos: tuple[float, float, float]) -> str:
    return f"{pos[0]: .3f} {pos[1]: .3f} {pos[2]: .3f}"


def header(case: dict[str, object], replicate: int, seed: int) -> str:
    return dedent(
        f"""\
        % Generated by ast/nuclear_aster_treadmilling_long_pilot/generate_treadmilling_long_pilot.py
        % Purpose: long treadmilling-only test for nucleus-bound actin turnover propulsion.
        % Case: {case["name"]}
        % Replicate: r{replicate:04d}
        % Description: {case["description"]}
        % Key setup: no chewers; actin starts at {INITIAL_LENGTH} um; max_length={MAX_LENGTH} um; total_polymer={TOTAL_POLYMER} um

        set simul system
        {{
            random_seed = {seed}
            steric    = 1, 500
            time_step = {TIME_STEP}
            kT        = 0.0042
            viscosity = 0.1
        }}
        set system display {{ back_color=white }}

        set space box {{ shape = rectangle }}
        new box {{ length = {BOX_LENGTH[0]}, {BOX_LENGTH[1]}, {BOX_LENGTH[2]} }}
        """
    )


def properties(case: dict[str, object]) -> str:
    text = dedent(
        f"""\

        set fiber ACTIN
        {{
            binding_key   = 1
            rigidity      = 0.075
            segmentation  = 0.10
            steric        = 1, 0.025
            confine       = inside, 200

            activity        = treadmill
            growing_speed   = 0.750, 0.00
            shrinking_speed = 0.00, -0.350
            growing_force   = inf, inf

            total_polymer = {TOTAL_POLYMER}
            max_length    = {MAX_LENGTH}
            display = ( color=black; line=3; )
        }}
        """
    )
    if bool(case["nucleator"]):
        text += dedent(
            """\

            set solid nucCore
            {
                viscosity = 20
                steric = 1, 0.025
                confine = inside, 200
                display = ( color=blue; style=3; )
            }

            set aster nucAster
            {
                stiffness = 1000, 500
                nucleate  = 3.0, ACTIN, ( plus_end=grow; minus_end=shrink; length=0.1; )
            }
            """
        )
    else:
        text += dedent(
            """\

            set bead nucBody
            {
                confine = inside, 200
                steric = 1
                display = ( color=blue; style=7; )
            }
            """
        )
    return text


def initial_objects(case: dict[str, object]) -> str:
    lines = [""]
    if bool(case["nucleator"]):
        fiber_spec = f"( plus_end=grow; minus_end=shrink; length={INITIAL_LENGTH}; )"
        if case["aster"] == "symmetric":
            lines.append(
                f"new 1 nucAster {{ solid=nucCore; type=regular; radius={NUCLEUS_RADIUS}, 0.10; "
                f"fibers={FIBER_COUNT}, ACTIN, {fiber_spec}; "
                f"position = {fmt_pos(NUCLEUS_START)}; }}"
            )
        elif case["aster"] == "cap":
            lines.append(
                f"new 1 nucAster {{ solid=nucCore; type=angular; direction = {case['direction']}; "
                f"aster_angle = {CAP_ANGLE_RAD}; radius={NUCLEUS_RADIUS}, 0.10; "
                f"fibers={FIBER_COUNT}, ACTIN, {fiber_spec}; "
                f"position = {fmt_pos(NUCLEUS_START)}; }}"
            )
        else:
            raise ValueError(f"unsupported aster type: {case['aster']}")
    else:
        lines.append(f"new 1 nucBody {{ radius = {NUCLEUS_RADIUS}; position = {fmt_pos(NUCLEUS_START)}; }}")
    return "\n".join(lines) + "\n"


def config_for(case: dict[str, object], replicate: int, seed: int, *, smoke: bool = False) -> str:
    steps = SMOKE_STEPS if smoke else RUN_STEPS
    frames = SMOKE_FRAMES if smoke else RUN_FRAMES
    text = header(case, replicate, seed)
    text += properties(case)
    text += initial_objects(case)
    text += f"\nrun {steps} system {{ nb_frames = {frames} }}\n"
    return text


def seed_for(case_index: int, replicate: int) -> int:
    return 78000 + case_index * 100 + replicate


def write_run(case: dict[str, object], case_index: int, replicate: int) -> dict[str, object]:
    seed = seed_for(case_index, replicate)
    run_dir = PRODUCTION / str(case["name"]) / f"r{replicate:04d}"
    run_dir.mkdir(parents=True, exist_ok=True)
    config = run_dir / "config.cym"
    config.write_text(config_for(case, replicate, seed), encoding="utf-8")
    (run_dir / "run.sh").write_text(
        dedent(
            """\
            #!/usr/bin/env bash
            set -euo pipefail
            root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../../../" && pwd)"
            "$root/sim" config.cym
            """
        ),
        encoding="utf-8",
    )
    (run_dir / "run.sh").chmod(0o755)
    return {
        "case": case["name"],
        "description": case["description"],
        "replicate": f"r{replicate:04d}",
        "seed": seed,
        "config": str(config.relative_to(ROOT)),
        "aster": case["aster"],
        "direction": case["direction"],
        "fiber_count": FIBER_COUNT if case["nucleator"] else 0,
        "initial_length_um": INITIAL_LENGTH,
        "max_length_um": MAX_LENGTH,
        "total_polymer_um": TOTAL_POLYMER,
        "duration_s": RUN_STEPS * TIME_STEP,
        "duration_min": RUN_STEPS * TIME_STEP / 60,
        "frames": RUN_FRAMES,
        "box_length": " ".join(str(v) for v in BOX_LENGTH),
    }


def write_smoke() -> None:
    case = CASES[1]
    SMOKE.mkdir(parents=True, exist_ok=True)
    (SMOKE / "config.cym").write_text(config_for(case, 1, 78999, smoke=True), encoding="utf-8")


def write_manifest(rows: list[dict[str, object]]) -> None:
    with (ROOT / "manifest.csv").open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    rows = []
    for case_index, case in enumerate(CASES, start=1):
        for replicate in range(1, REPLICATES + 1):
            rows.append(write_run(case, case_index, replicate))
    write_smoke()
    write_manifest(rows)
    print(f"Wrote {len(rows)} production configs under {PRODUCTION}")
    print(f"Wrote smoke config under {SMOKE}")


if __name__ == "__main__":
    main()
