#!/usr/bin/env python3
"""Generate small nuclear-propulsion mechanism mockups.

The goal is not a production sweep. These configs isolate physical ingredients:
geometry-only asters, fixed external binders, fixed external motors, and
lab-frame polymerization push with and without anchoring.
"""

from __future__ import annotations

import csv
from pathlib import Path
from textwrap import dedent


ROOT = Path(__file__).resolve().parent
PRODUCTION = ROOT / "production"
SMOKE = ROOT / "00_smoke_all_cases"
QUICK = ROOT / "01_quick_20s"

TIME_STEP = 0.005
RUN_STEPS = 18000  # 90 s
RUN_FRAMES = 90
QUICK_STEPS = 4000  # 20 s
QUICK_FRAMES = 20
SMOKE_STEPS = 800  # 4 s
SMOKE_FRAMES = 8
REPLICATES = 3

BOX_LENGTH = (18.0, 9.0, 1.4)
NUCLEUS_START = (0.0, 0.0, 0.0)
NUCLEUS_RADIUS = 0.5
NUCLEUS_VISCOSITY = 80

ASTER_FIBERS = 56
PUSH_FIBERS = 48
INITIAL_ASTER_LENGTH = 1.1
INITIAL_PUSH_LENGTH = 0.35
MAX_LENGTH = 3.0
TOTAL_POLYMER = 12000
CAP_ANGLE_RAD = 0.85

MOTOR_PATCH_X = 1.65
PUSH_SOURCE_X = -1.18

CASES = [
    {
        "name": "01_symmetric_aster_no_external",
        "description": "Symmetric nucleus-bound aster; no external traction.",
        "mode": "aster",
        "aster": "symmetric",
        "external": "none",
    },
    {
        "name": "02_plus_x_cap_no_external",
        "description": "Plus-x one-sided aster; geometry-only directional-bias control.",
        "mode": "aster",
        "aster": "plus_x_cap",
        "external": "none",
    },
    {
        "name": "03_plus_x_cap_fixed_binders",
        "description": "Plus-x one-sided aster with fixed non-motor binders on the plus-x side.",
        "mode": "aster",
        "aster": "plus_x_cap",
        "external": "binders",
    },
    {
        "name": "04_plus_x_cap_fixed_plus_motors",
        "description": "Plus-x one-sided aster with fixed plus-end-directed motors on the plus-x side.",
        "mode": "aster",
        "aster": "plus_x_cap",
        "external": "plus_motors",
    },
    {
        "name": "05_symmetric_aster_fixed_plus_motors",
        "description": "Symmetric aster with one-sided fixed plus-end-directed motors.",
        "mode": "aster",
        "aster": "symmetric",
        "external": "plus_motors",
    },
    {
        "name": "06_plus_x_cap_fixed_minus_motors",
        "description": "Plus-x one-sided aster with fixed minus-end-directed motors on the plus-x side.",
        "mode": "aster",
        "aster": "plus_x_cap",
        "external": "minus_motors",
    },
    {
        "name": "07_symmetric_aster_fixed_minus_motors",
        "description": "Symmetric aster with one-sided fixed minus-end-directed motors.",
        "mode": "aster",
        "aster": "symmetric",
        "external": "minus_motors",
    },
    {
        "name": "08_push_filaments_unanchored",
        "description": "Lab-frame filaments seeded on the minus-x side and growing toward the nucleus; no anchors.",
        "mode": "push",
        "external": "none",
    },
    {
        "name": "09_push_filaments_fixed_binders",
        "description": "Lab-frame growing filaments aimed at the nucleus, with fixed binders anchoring the minus-x side.",
        "mode": "push",
        "external": "push_binders",
    },
    {
        "name": "10_push_filaments_fixed_plus_motors",
        "description": "Lab-frame growing filaments aimed at the nucleus, with fixed motors on the minus-x side.",
        "mode": "push",
        "external": "push_plus_motors",
    },
]


def fmt_pos(pos: tuple[float, float, float]) -> str:
    return f"{pos[0]: .3f} {pos[1]: .3f} {pos[2]: .3f}"


def run_length(*, smoke: bool = False, quick: bool = False) -> tuple[int, int]:
    if smoke:
        return SMOKE_STEPS, SMOKE_FRAMES
    if quick:
        return QUICK_STEPS, QUICK_FRAMES
    return RUN_STEPS, RUN_FRAMES


def header(case: dict[str, str], replicate: int, seed: int, *, smoke: bool, quick: bool) -> str:
    steps, frames = run_length(smoke=smoke, quick=quick)
    return dedent(
        f"""\
        % Generated by ast/nuclear_propulsion_mechanism_mockups/generate_mechanism_mockups.py
        % Purpose: minimal mechanism screen for directed nuclear motion.
        % Case: {case["name"]}
        % Replicate: r{replicate:04d}
        % Description: {case["description"]}
        % Duration: {steps * TIME_STEP:.3f} s; frames={frames}

        set simul system
        {{
            random_seed = {seed}
            steric    = 1, 500
            time_step = {TIME_STEP}
            kT        = 0.0042
            viscosity = 0.1
        }}
        set system display {{ back_color=white }}

        set space box {{ shape = rectangle }}
        new box {{ length = {BOX_LENGTH[0]}, {BOX_LENGTH[1]}, {BOX_LENGTH[2]} }}
        """
    )


def properties(case: dict[str, str]) -> str:
    return dedent(
        f"""\

        set fiber ACTIN
        {{
            binding_key   = 1
            rigidity      = 0.075
            segmentation  = 0.10
            steric        = 1, 0.025
            confine       = inside, 200

            activity        = treadmill
            growing_speed   = 0.65, 0.00
            shrinking_speed = 0.00, -0.25
            growing_force   = inf, inf

            total_polymer = {TOTAL_POLYMER}
            max_length    = {MAX_LENGTH}
            display = ( color=black; line=3; )
        }}

        set hand cortex_binder_hand
        {{
            binding_key     = 1
            binding         = 12, 0.180
            unbinding       = 0.050, 5
            display = ( color=cyan; )
        }}

        set hand cortex_motor_plus
        {{
            binding_key     = 1
            binding         = 12, 0.180
            unbinding       = 0.120, 5
            activity        = move
            unloaded_speed  = 0.35
            stall_force     = 5
            display = ( color=red; )
        }}

        set hand cortex_motor_minus
        {{
            binding_key     = 1
            binding         = 12, 0.180
            unbinding       = 0.120, 5
            activity        = move
            unloaded_speed  = -0.35
            stall_force     = 5
            display = ( color=orange; )
        }}

        set single fixed_binder
        {{
            hand = cortex_binder_hand
            activity = fixed
            stiffness = 25
            diffusion = 0
            save_unbound = 1
        }}

        set single fixed_motor_plus
        {{
            hand = cortex_motor_plus
            activity = fixed
            stiffness = 25
            diffusion = 0
            save_unbound = 1
        }}

        set single fixed_motor_minus
        {{
            hand = cortex_motor_minus
            activity = fixed
            stiffness = 25
            diffusion = 0
            save_unbound = 1
        }}

        set solid nucCore
        {{
            viscosity = {NUCLEUS_VISCOSITY}
            steric = 1, 0.050
            confine = inside, 200
            display = ( color=blue; style=3; )
        }}

        set bead nucBody
        {{
            viscosity = {NUCLEUS_VISCOSITY}
            steric = 1, 0.050
            confine = inside, 200
            display = ( color=blue; style=7; )
        }}

        set aster nucAster
        {{
            stiffness = 1000, 500
            nucleate  = 1.0, ACTIN, ( plus_end=grow; minus_end=shrink; length={INITIAL_ASTER_LENGTH}; )
        }}
        """
    )


def aster_objects(case: dict[str, str]) -> list[str]:
    fiber_spec = (
        f"( plus_end=grow; minus_end=shrink; length={INITIAL_ASTER_LENGTH}; )"
    )
    if case["aster"] == "symmetric":
        return [
            "new 1 nucAster { "
            f"solid=nucCore; type=regular; radius={NUCLEUS_RADIUS}, 0.10; "
            f"fibers={ASTER_FIBERS}, ACTIN, {fiber_spec}; "
            f"position = {fmt_pos(NUCLEUS_START)}; }}"
        ]
    if case["aster"] == "plus_x_cap":
        return [
            "new 1 nucAster { "
            "solid=nucCore; type=angular; direction = 1 0 0; "
            f"aster_angle = {CAP_ANGLE_RAD}; radius={NUCLEUS_RADIUS}, 0.10; "
            f"fibers={ASTER_FIBERS}, ACTIN, {fiber_spec}; "
            f"position = {fmt_pos(NUCLEUS_START)}; }}"
        ]
    raise ValueError(f"unsupported aster mode: {case['aster']}")


def push_objects() -> list[str]:
    return [
        f"new 1 nucBody {{ radius = {NUCLEUS_RADIUS}; position = {fmt_pos(NUCLEUS_START)}; }}",
        "new "
        f"{PUSH_FIBERS} ACTIN {{ "
        f"position = rectangle 0.70 1.80 0.70 at {PUSH_SOURCE_X:.3f} 0 0; "
        "direction = 1 0 0; "
        f"length = {INITIAL_PUSH_LENGTH}; plus_end = grow; minus_end = shrink; "
        "placement = anywhere; "
        "}",
    ]


def external_objects(case: dict[str, str]) -> list[str]:
    ext = case["external"]
    if ext == "none":
        return []
    if ext == "binders":
        return [
            "new 80 fixed_binder { "
            f"position = rectangle 1.10 2.20 0.80 at {MOTOR_PATCH_X:.3f} 0 0; "
            "placement = anywhere; }"
        ]
    if ext == "plus_motors":
        return [
            "new 80 fixed_motor_plus { "
            f"position = rectangle 1.10 2.20 0.80 at {MOTOR_PATCH_X:.3f} 0 0; "
            "placement = anywhere; }"
        ]
    if ext == "minus_motors":
        return [
            "new 80 fixed_motor_minus { "
            f"position = rectangle 1.10 2.20 0.80 at {MOTOR_PATCH_X:.3f} 0 0; "
            "placement = anywhere; }"
        ]
    if ext == "push_binders":
        return [
            "new 80 fixed_binder { "
            f"position = rectangle 0.80 2.20 0.80 at {PUSH_SOURCE_X - 0.20:.3f} 0 0; "
            "placement = anywhere; }"
        ]
    if ext == "push_plus_motors":
        return [
            "new 80 fixed_motor_plus { "
            f"position = rectangle 0.80 2.20 0.80 at {PUSH_SOURCE_X - 0.20:.3f} 0 0; "
            "placement = anywhere; }"
        ]
    raise ValueError(f"unsupported external mode: {ext}")


def config_for(case: dict[str, str], replicate: int, seed: int, *, smoke: bool = False, quick: bool = False) -> str:
    steps, frames = run_length(smoke=smoke, quick=quick)
    lines = [header(case, replicate, seed, smoke=smoke, quick=quick), properties(case), ""]
    if case["mode"] == "aster":
        lines.extend(aster_objects(case))
    elif case["mode"] == "push":
        lines.extend(push_objects())
    else:
        raise ValueError(f"unsupported mode: {case['mode']}")
    lines.extend(external_objects(case))
    lines.append("")
    lines.append(f"run {steps} system {{ nb_frames = {frames} }}")
    return "\n".join(lines) + "\n"


def seed_for(case_index: int, replicate: int) -> int:
    return 91000 + case_index * 100 + replicate


def write_run(case: dict[str, str], case_index: int, replicate: int) -> dict[str, object]:
    seed = seed_for(case_index, replicate)
    run_dir = PRODUCTION / case["name"] / f"r{replicate:04d}"
    run_dir.mkdir(parents=True, exist_ok=True)
    config = run_dir / "config.cym"
    config.write_text(config_for(case, replicate, seed), encoding="utf-8")
    (run_dir / "run.sh").write_text(
        dedent(
            """\
            #!/usr/bin/env bash
            set -euo pipefail
            root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../../../" && pwd)"
            "$root/build_mini_turnover/bin/sim" config.cym
            """
        ),
        encoding="utf-8",
    )
    (run_dir / "run.sh").chmod(0o755)
    return {
        "case": case["name"],
        "description": case["description"],
        "mode": case["mode"],
        "aster": case.get("aster", ""),
        "external": case["external"],
        "replicate": f"r{replicate:04d}",
        "seed": seed,
        "config": str(config.relative_to(ROOT)),
        "duration_s": RUN_STEPS * TIME_STEP,
        "duration_min": RUN_STEPS * TIME_STEP / 60,
        "frames": RUN_FRAMES,
        "nucleus_viscosity": NUCLEUS_VISCOSITY,
        "box_length": " ".join(str(v) for v in BOX_LENGTH),
        "aster_fibers": ASTER_FIBERS if case["mode"] == "aster" else 0,
        "push_fibers": PUSH_FIBERS if case["mode"] == "push" else 0,
        "max_length_um": MAX_LENGTH,
    }


def write_smoke() -> None:
    for idx, case in enumerate(CASES, start=1):
        run_dir = SMOKE / case["name"]
        run_dir.mkdir(parents=True, exist_ok=True)
        (run_dir / "config.cym").write_text(
            config_for(case, 1, seed_for(idx, 1), smoke=True),
            encoding="utf-8",
        )


def write_quick() -> None:
    for idx, case in enumerate(CASES, start=1):
        run_dir = QUICK / case["name"] / "r0001"
        run_dir.mkdir(parents=True, exist_ok=True)
        (run_dir / "config.cym").write_text(
            config_for(case, 1, seed_for(idx, 1), quick=True),
            encoding="utf-8",
        )


def write_manifest(rows: list[dict[str, object]]) -> None:
    with (ROOT / "manifest.csv").open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    rows = []
    for case_index, case in enumerate(CASES, start=1):
        for replicate in range(1, REPLICATES + 1):
            rows.append(write_run(case, case_index, replicate))
    write_smoke()
    write_quick()
    write_manifest(rows)
    print(f"Wrote {len(rows)} production configs under {PRODUCTION}")
    print(f"Wrote {len(CASES)} smoke configs under {SMOKE}")
    print(f"Wrote {len(CASES)} quick-look configs under {QUICK}")


if __name__ == "__main__":
    main()
