#!/usr/bin/env python3
"""Generate short, one-sided nuclear-aster turnover propulsion pilot configs."""

from __future__ import annotations

import csv
from pathlib import Path
from textwrap import dedent


ROOT = Path(__file__).resolve().parent
RUN_STEPS = 12000  # 60 s at dt = 0.005 s
RUN_FRAMES = 60
REPLICATES = 3
NUCLEUS_START = (-3.0, 0.0, 0.0)
TURNOVER_ONSET_S = 4.0

FIBER_COUNT = 24
MAX_LENGTH = 2.5
INITIAL_LENGTH = 2.0
CAP_ANGLE_RAD = 0.85  # ~49 degrees around the chosen nucleus side
TURNOVER_SIDE_X = NUCLEUS_START[0] - 0.82

CASES = [
    {
        "name": "01_symmetric_short_no_chewer",
        "description": "Symmetric short nucleus-bound aster without localized turnover factors.",
        "aster": "symmetric",
        "chewers": "none",
        "nucleator": True,
    },
    {
        "name": "02_symmetric_short_one_sided_chewer",
        "description": "Symmetric short nucleus-bound aster with fixed turnover factors on the minus-x side.",
        "aster": "symmetric",
        "chewers": "minus_x_fixed",
        "nucleator": True,
    },
    {
        "name": "03_cap_short_no_chewer",
        "description": "One-sided minus-x angular-cap aster without localized turnover factors.",
        "aster": "minus_x_cap",
        "chewers": "none",
        "nucleator": True,
    },
    {
        "name": "04_cap_short_one_sided_chewer",
        "description": "One-sided minus-x angular-cap aster with fixed turnover factors on the same side.",
        "aster": "minus_x_cap",
        "chewers": "minus_x_fixed",
        "nucleator": True,
    },
    {
        "name": "05_no_nucleator_fixed_chewer_control",
        "description": "Nucleus body with fixed one-sided turnover factors but no actin nucleator.",
        "aster": "none",
        "chewers": "minus_x_fixed",
        "nucleator": False,
    },
    {
        "name": "06_symmetric_short_delayed_one_sided_chewer",
        "description": "Symmetric short aster; one-sided fixed turnover factors introduced after filaments reach the length cap.",
        "aster": "symmetric",
        "chewers": "delayed_minus_x_fixed",
        "nucleator": True,
    },
    {
        "name": "07_cap_short_delayed_one_sided_chewer",
        "description": "One-sided minus-x angular-cap aster; same-side fixed turnover factors introduced after filaments reach the length cap.",
        "aster": "minus_x_cap",
        "chewers": "delayed_minus_x_fixed",
        "nucleator": True,
    },
]


def fmt_pos(pos: tuple[float, float, float]) -> str:
    return f"{pos[0]: .3f} {pos[1]: .3f} {pos[2]: .3f}"


def header(case: dict[str, object], replicate: int, seed: int) -> str:
    return dedent(
        f"""\
        % Generated by ast/nuclear_aster_one_sided_turnover_pilot/generate_one_sided_turnover_pilot.py
        % Purpose: short-filament test for one-sided nucleus-proximal actin turnover.
        % Case: {case["name"]}
        % Replicate: r{replicate:04d}
        % Description: {case["description"]}
        % Filament cap: max_length={MAX_LENGTH} um; initial_length={INITIAL_LENGTH} um

        set simul system
        {{
            random_seed = {seed}
            steric    = 1, 500
            time_step = 0.005
            kT        = 0.0042
            viscosity = 0.1
        }}
        set system display {{ back_color=white }}

        set space box {{ shape = rectangle }}
        new box {{ length = 16, 8, 1.2 }}
        """
    )


def common_properties(case: dict[str, object]) -> str:
    text = dedent(
        f"""\

        set fiber ACTIN
        {{
            binding_key   = 1
            rigidity      = 0.075
            segmentation  = 0.12
            steric        = 1, 0.025
            confine       = inside, 200

            activity        = treadmill
            growing_speed   = 0.750, 0.00
            shrinking_speed = 0.00, -0.350
            growing_force   = inf, inf

            total_polymer = 160
            max_length    = {MAX_LENGTH}
            display = ( color=black; line=3; )
        }}

        set hand actin_binder
        {{
            binding_key     = 1
            binding_rate    = 5
            binding_range   = 0.150
            unbinding_rate  = 0.2
            unbinding_force = 5
            display = ( color=cyan; )
        }}

        set couple xlk_par
        {{
            hand1 = actin_binder
            hand2 = actin_binder
            stiffness = 1
            diffusion = 10
            activity = crosslink
            specificity = parallel
        }}

        set couple xlk_anti
        {{
            hand1 = actin_binder
            hand2 = actin_binder
            stiffness = 1
            diffusion = 10
            activity = crosslink
            specificity = antiparallel
        }}

        set hand actin_chewer
        {{
            binding_key = 1
            binding = 12, 0.180
            unbinding = 0.4, 3
            activity = chew
            bind_also_end = both_ends
            hold_growing_end = 1
            hold_shrinking_end = 1
            chewing_speed = 0.120
            display = ( color=magenta; )
        }}

        set single actin_chewer_fixed
        {{
            hand = actin_chewer
            activity = fixed
            stiffness = 0
            diffusion = 0
            save_unbound = 1
        }}
        """
    )
    if bool(case["nucleator"]):
        text += dedent(
            """\

            set solid nucCore
            {
                steric = 1, 0.025
                confine = inside, 200
                display = ( color=blue; style=3; )
            }

            set aster nucAster
            {
                stiffness = 1000, 500
                nucleate  = 1.5, ACTIN, ( plus_end=grow; minus_end=shrink; length=2.0; )
            }
            """
        )
    else:
        text += dedent(
            """\

            set bead nucBody
            {
                confine = inside, 200
                steric = 1
                display = ( color=blue; style=7; )
            }
            """
        )
    return text


def initial_objects(case: dict[str, object]) -> str:
    lines = [""]
    if bool(case["nucleator"]):
        fiber_spec = f"( plus_end=grow; minus_end=shrink; length={INITIAL_LENGTH}; )"
        if case["aster"] == "symmetric":
            lines.append(
                "new 1 nucAster { solid=nucCore; type=regular; radius=0.5, 0.12; "
                f"fibers={FIBER_COUNT}, ACTIN, {fiber_spec}; "
                f"position = {fmt_pos(NUCLEUS_START)}; }}"
            )
        elif case["aster"] == "minus_x_cap":
            lines.append(
                "new 1 nucAster { solid=nucCore; type=angular; direction = -1 0 0; "
                f"aster_angle = {CAP_ANGLE_RAD}; radius=0.5, 0.12; "
                f"fibers={FIBER_COUNT}, ACTIN, {fiber_spec}; "
                f"position = {fmt_pos(NUCLEUS_START)}; }}"
            )
        else:
            raise ValueError(f"unsupported aster type: {case['aster']}")
    else:
        lines.append(f"new 1 nucBody {{ radius = 0.5; position = {fmt_pos(NUCLEUS_START)}; }}")

    lines.append("new 24 xlk_par  { position = inside; }")
    lines.append("new 24 xlk_anti { position = inside; }")

    if case["chewers"] == "minus_x_fixed":
        # Fixed turnover factors are placed in a slab outside the minus-x face of the nucleus.
        # This is static in the lab frame, so it is only a first-pass proxy for a nucleus-bound ACTIN10 cap.
        lines.append(
            f"new 36 actin_chewer_fixed {{ position = rectangle 0.42 1.15 0.42 at {TURNOVER_SIDE_X:.3f} 0 0; "
            "placement = anywhere; }"
        )
    elif case["chewers"] != "none":
        if case["chewers"] == "delayed_minus_x_fixed":
            return "\n".join(lines) + "\n"
        raise ValueError(f"unsupported chewer mode: {case['chewers']}")
    return "\n".join(lines) + "\n"


def config_for(case: dict[str, object], replicate: int, seed: int) -> str:
    text = header(case, replicate, seed)
    text += common_properties(case)
    text += initial_objects(case)
    if case["chewers"] == "delayed_minus_x_fixed":
        text += dedent(
            f"""\

            new event
            {{
                time = {TURNOVER_ONSET_S}
                code = (
                    new 36 actin_chewer_fixed {{ position = rectangle 0.42 1.15 0.42 at {TURNOVER_SIDE_X:.3f} 0 0; placement = anywhere; }}
                )
            }}
            """
        )
    text += f"\nrun {RUN_STEPS} system {{ nb_frames = {RUN_FRAMES} }}\n"
    return text


def seed_for(case_index: int, replicate: int) -> int:
    return 76000 + case_index * 100 + replicate


def write_case(case: dict[str, object], case_index: int, replicate: int) -> dict[str, object]:
    seed = seed_for(case_index, replicate)
    run_dir = ROOT / str(case["name"]) / f"r{replicate:04d}"
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "config.cym").write_text(config_for(case, replicate, seed), encoding="utf-8")
    (run_dir / "run.sh").write_text(
        dedent(
            """\
            #!/usr/bin/env bash
            set -euo pipefail
            root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)"
            "$root/sim" config.cym
            """
        ),
        encoding="utf-8",
    )
    (run_dir / "run.sh").chmod(0o755)
    return {
        "case": case["name"],
        "description": case["description"],
        "replicate": f"r{replicate:04d}",
        "seed": seed,
        "config": str((run_dir / "config.cym").relative_to(ROOT)),
        "aster": case["aster"],
        "chewers": case["chewers"],
        "fiber_count": FIBER_COUNT if case["nucleator"] else 0,
        "initial_length_um": INITIAL_LENGTH,
        "max_length_um": MAX_LENGTH,
        "cap_angle_rad": CAP_ANGLE_RAD if case["aster"] == "minus_x_cap" else "",
        "steps": RUN_STEPS,
        "frames": RUN_FRAMES,
        "duration_s": RUN_STEPS * 0.005,
        "turnover_onset_s": TURNOVER_ONSET_S if case["chewers"] == "delayed_minus_x_fixed" else "",
    }


def write_manifest(rows: list[dict[str, object]]) -> None:
    with (ROOT / "manifest.csv").open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    rows = []
    for case_index, case in enumerate(CASES, start=1):
        for replicate in range(1, REPLICATES + 1):
            rows.append(write_case(case, case_index, replicate))
    write_manifest(rows)
    print(f"Wrote {len(rows)} configs under {ROOT}")


if __name__ == "__main__":
    main()
