#!/usr/bin/env python3
"""Generate replicated fixed-MT versus growing-MT endosperm configs."""

from __future__ import annotations

import csv
from pathlib import Path
from textwrap import dedent


ROOT = Path(__file__).resolve().parent

RUN_STEPS_5MIN = 60000
RUN_FRAMES = 150
DIVISION_TIME = 120
REPLICATES = 5

BASE_ACTIN_TOTAL_POLYMER = 1200
ACTIN_MAX_LENGTH = 16
BASE_UNIFORM_ACTIN = 48
BASE_PERINUCLEAR_ACTIN_PER_SITE = 12
BASE_XLINK_PAR = 48
BASE_XLINK_ANTI = 48
BASE_DIVISION_XLINK_PAR = 24
BASE_DIVISION_XLINK_ANTI = 24
BASE_RENUCLEATION_PER_SITE = 1

SYSTEMS = [
    {
        "id": "small_system",
        "label": "small 12x12x1.2 um",
        "box": (12.0, 12.0, 1.2),
        "scale_factor": 1.0,
        "material_scale": 1,
        "nuclei_4": [(-3.0, -2.0, 0.0), (3.0, -2.0, 0.0), (-3.0, 2.0, 0.0), (3.0, 2.0, 0.0)],
        "nuclei_2": [(-3.0, -2.0, 0.0), (3.0, -2.0, 0.0)],
        "division_new": [(-3.0, 2.0, 0.0), (3.0, 2.0, 0.0)],
        "fixed_mt_length": 6.0,
        "mt_fibers_per_site": 8,
        "seed_offset": 0,
    },
    {
        "id": "large_system",
        "label": "large 24x24x1.2 um",
        "box": (24.0, 24.0, 1.2),
        "scale_factor": 2.0,
        "material_scale": 4,
        "nuclei_4": [(-6.0, -6.0, 0.0), (6.0, -6.0, 0.0), (-6.0, 6.0, 0.0), (6.0, 6.0, 0.0)],
        "nuclei_2": [(-6.0, -6.0, 0.0), (6.0, -6.0, 0.0)],
        "division_new": [(-6.0, 6.0, 0.0), (6.0, 6.0, 0.0)],
        "fixed_mt_length": 12.0,
        "mt_fibers_per_site": 16,
        "seed_offset": 10000,
    },
]

CASES = [
    {
        "index": 1,
        "name": "01_actin_only_perinuclear_long",
        "description": "Long free perinuclear actin control with doubled actin polymer pool.",
        "microtubules": False,
        "mt_mode": "none",
        "actin_mode": "perinuclear",
        "division": False,
        "steric": 1,
    },
    {
        "index": 2,
        "name": "02_fixed_mt_uniform_actin_long",
        "description": "Fixed-length tethered MT asters, uniform free actin, doubled actin pool.",
        "microtubules": True,
        "mt_mode": "fixed",
        "actin_mode": "uniform",
        "division": False,
        "steric": 1,
    },
    {
        "index": 3,
        "name": "03_growing_mt_uniform_actin_long",
        "description": "Growing tethered MT asters from short seeds, uniform free actin, doubled actin pool.",
        "microtubules": True,
        "mt_mode": "growing",
        "actin_mode": "uniform",
        "division": False,
        "steric": 1,
    },
    {
        "index": 4,
        "name": "04_fixed_mt_perinuclear_actin_long",
        "description": "Fixed-length tethered MT asters, free perinuclear actin, doubled actin pool.",
        "microtubules": True,
        "mt_mode": "fixed",
        "actin_mode": "perinuclear",
        "division": False,
        "steric": 1,
    },
    {
        "index": 5,
        "name": "05_growing_mt_perinuclear_actin_long",
        "description": "Growing tethered MT asters from short seeds, free perinuclear actin, doubled actin pool.",
        "microtubules": True,
        "mt_mode": "growing",
        "actin_mode": "perinuclear",
        "division": False,
        "steric": 1,
    },
    {
        "index": 6,
        "name": "06_division_fixed_mt_perinuclear_actin_long",
        "description": "Two-to-four division with fixed-length tethered MTs and free perinuclear actin.",
        "microtubules": True,
        "mt_mode": "fixed",
        "actin_mode": "perinuclear",
        "division": True,
        "steric": 1,
    },
    {
        "index": 7,
        "name": "07_division_growing_mt_perinuclear_actin_long",
        "description": "Two-to-four division with growing tethered MTs and free perinuclear actin.",
        "microtubules": True,
        "mt_mode": "growing",
        "actin_mode": "perinuclear",
        "division": True,
        "steric": 1,
    },
]


def scaled(system: dict[str, object], value: int) -> int:
    return int(value) * int(system["material_scale"])


def fmt_pos(pos: tuple[float, float, float]) -> str:
    return f"{pos[0]: .3f} {pos[1]: .3f} {pos[2]: .3f}"


def header(case: dict[str, object], system: dict[str, object], replicate: int, steps: int, frames: int, seed: int) -> str:
    steric_strength = "1, 500" if int(case["steric"]) else "0"
    box_x, box_y, box_z = system["box"]
    return dedent(
        f"""\
        % Generated by ast/tethered_mt_free_actin_long_replicates/generate_tethered_mt_free_actin_long_replicates.py
        % Planner target: replicated tethered microtubules plus free actin, no direct actin-MT binding.
        % System: {system["id"]} ({system["label"]})
        % Case: {case["name"]}
        % Replicate: r{replicate:04d}
        % Description: {case["description"]}
        % Actin total_polymer = {scaled(system, BASE_ACTIN_TOTAL_POLYMER)} um; actin max_length = {ACTIN_MAX_LENGTH} um.
        % Fixed MT length = {system["fixed_mt_length"]} um.

        set simul system
        {{
            random_seed = {seed}
            steric    = {steric_strength}
            time_step = 0.005
            kT        = 0.0042
            viscosity = 0.1
        }}
        set system display {{ back_color=white }}

        set space box {{ shape = rectangle }}
        new box {{ length = {box_x:g}, {box_y:g}, {box_z:g} }}
        """
    )


def actin_properties(system: dict[str, object]) -> str:
    return dedent(
        f"""\

        set fiber ACTIN
        {{
            binding_key   = 1
            rigidity      = 0.075
            segmentation  = 0.12
            steric        = 1, 0.025
            confine       = inside, 200

            activity        = treadmill
            growing_speed   = 0.20, 0.00
            shrinking_speed = 0.00, -0.05
            growing_force   = inf, inf

            total_polymer = {scaled(system, BASE_ACTIN_TOTAL_POLYMER)}
            max_length    = {ACTIN_MAX_LENGTH}
            display = ( color=black; line=3; )
        }}

        set hand actin_binder
        {{
            binding_key     = 1
            binding_rate    = 5
            binding_range   = 0.150
            unbinding_rate  = 0.2
            unbinding_force = 5
            display = ( color=cyan; )
        }}

        set couple xlk_par
        {{
            hand1 = actin_binder
            hand2 = actin_binder
            stiffness = 1
            diffusion = 10
            activity = crosslink
            specificity = parallel
        }}

        set couple xlk_anti
        {{
            hand1 = actin_binder
            hand2 = actin_binder
            stiffness = 1
            diffusion = 10
            activity = crosslink
            specificity = antiparallel
        }}
        """
    )


def mt_properties(system: dict[str, object], mt_mode: str) -> str:
    if mt_mode == "none":
        return ""
    activity_block = ""
    if mt_mode == "growing":
        activity_block = dedent(
            """\

                activity          = classic
                growing_speed     = 0.35
                shrinking_speed   = -0.60
                catastrophe_rate  = 0.04, 0.20
                rescue_rate       = 0.05
                growing_force     = 1.67
                persistent        = 1
                min_length        = 0.3
                total_polymer     = inf
            """
        )
    elif mt_mode != "fixed":
        raise ValueError(f"unknown mt_mode: {mt_mode}")

    return dedent(
        f"""\

        set fiber MT
        {{
            binding_key   = 3
            rigidity      = 20
            segmentation  = 0.25
            steric        = 1, 0.025
            confine       = inside, 200
        {activity_block}
            display = ( color=green; plus_end=white, 3; line=4; )
        }}

        set solid nucCore
        {{
            steric = 1, 0.025
            display = ( color=blue; style=3; )
        }}

        set aster mtTether
        {{
            stiffness = 1000, 500
            nucleate  = 1, MT, ( {mt_fiber_state(system, mt_mode, initial=True)} )
        }}
        """
    )


def nucleus_bead_properties() -> str:
    return dedent(
        """\

        set bead nucBody
        {
            confine = inside, 200
            steric = 1
            display = ( color=blue; style=7; )
        }
        """
    )


def mt_fiber_state(system: dict[str, object], mt_mode: str, initial: bool = False) -> str:
    if mt_mode == "fixed":
        return f"length={float(system['fixed_mt_length']):g};"
    if mt_mode == "growing":
        return "plus_end=grow; length=0.8;" if initial else "plus_end=grow; length=1.0;"
    raise ValueError(f"unknown mt_mode: {mt_mode}")


def add_nuclei_without_mt(positions: list[tuple[float, float, float]]) -> str:
    lines = [""]
    for pos in positions:
        lines.append(f"new 1 nucBody {{ radius = 0.5; position = {fmt_pos(pos)}; }}")
    return "\n".join(lines) + "\n"


def add_tethered_mt_sites(system: dict[str, object], positions: list[tuple[float, float, float]], mt_mode: str) -> str:
    lines = [""]
    fibers_per_site = int(system["mt_fibers_per_site"])
    for pos in positions:
        lines.append(
            "new 1 mtTether { solid=nucCore; radius=0.5; point1=center, 0.5; "
            f"fibers={fibers_per_site}, MT, ( {mt_fiber_state(system, mt_mode)} ); position = {fmt_pos(pos)}; }}"
        )
    return "\n".join(lines) + "\n"


def add_actin_initial(system: dict[str, object], positions: list[tuple[float, float, float]], mode: str) -> str:
    lines = [""]
    if mode == "uniform":
        lines.append(
            f"new {scaled(system, BASE_UNIFORM_ACTIN)} ACTIN "
            "{ position = inside; length = 1.5; plus_end = grow; minus_end = shrink; }"
        )
    elif mode == "perinuclear":
        count = scaled(system, BASE_PERINUCLEAR_ACTIN_PER_SITE)
        for pos in positions:
            lines.append(
                f"new {count} ACTIN {{ position = disc 1.3 0.35 at {fmt_pos(pos)}; "
                "length = 1.5; plus_end = grow; minus_end = shrink; }"
            )
    else:
        raise ValueError(f"unknown actin_mode: {mode}")
    lines.append(f"new {scaled(system, BASE_XLINK_PAR)} xlk_par  {{ position = inside; }}")
    lines.append(f"new {scaled(system, BASE_XLINK_ANTI)} xlk_anti {{ position = inside; }}")
    return "\n".join(lines) + "\n"


def actin_renucleation_event(
    system: dict[str, object], positions: list[tuple[float, float, float]], start: int | None = None
) -> str:
    lines = ["", "new event", "{", "    delay = 10"]
    if start is not None:
        lines.append(f"    start = {start}")
    lines.extend(["    stop = 300", "    code = ("])
    count = scaled(system, BASE_RENUCLEATION_PER_SITE)
    for pos in positions:
        lines.append(
            f"        new {count} ACTIN {{ position = disc 1.3 0.35 at {fmt_pos(pos)}; "
            "length = 0.5; plus_end = grow; minus_end = shrink; }"
        )
    lines.extend(["    )", "}", ""])
    return "\n".join(lines)


def division_event(case: dict[str, object], system: dict[str, object]) -> str:
    mt_mode = str(case["mt_mode"])
    new_positions = list(system["division_new"])
    lines = ["", "new event", "{", f"    time = {DIVISION_TIME}", "    code = ("]
    if bool(case["microtubules"]):
        fibers_per_site = int(system["mt_fibers_per_site"])
        for pos in new_positions:
            lines.append(
                "        new 1 mtTether { solid=nucCore; radius=0.5; point1=center, 0.5; "
                f"fibers={fibers_per_site}, MT, ( {mt_fiber_state(system, mt_mode)} ); position = {fmt_pos(pos)}; }}"
            )
    else:
        for pos in new_positions:
            lines.append(f"        new 1 nucBody {{ radius = 0.5; position = {fmt_pos(pos)}; }}")
    count = scaled(system, BASE_PERINUCLEAR_ACTIN_PER_SITE)
    for pos in new_positions:
        lines.append(
            f"        new {count} ACTIN {{ position = disc 1.3 0.35 at {fmt_pos(pos)}; "
            "length = 1.5; plus_end = grow; minus_end = shrink; }"
        )
    lines.append(f"        new {scaled(system, BASE_DIVISION_XLINK_PAR)} xlk_par  {{ position = inside; }}")
    lines.append(f"        new {scaled(system, BASE_DIVISION_XLINK_ANTI)} xlk_anti {{ position = inside; }}")
    lines.extend(["    )", "}", ""])
    return "\n".join(lines)


def config_for(case: dict[str, object], system: dict[str, object], replicate: int, steps: int, frames: int, seed: int) -> str:
    positions = list(system["nuclei_2"] if bool(case["division"]) else system["nuclei_4"])
    text = header(case, system, replicate, steps, frames, seed)
    text += actin_properties(system)
    text += mt_properties(system, str(case["mt_mode"]))
    if bool(case["microtubules"]):
        text += add_tethered_mt_sites(system, positions, str(case["mt_mode"]))
    else:
        text += nucleus_bead_properties()
        text += add_nuclei_without_mt(positions)
    text += add_actin_initial(system, positions, str(case["actin_mode"]))
    if str(case["actin_mode"]) == "perinuclear":
        text += actin_renucleation_event(system, positions)
    if bool(case["division"]):
        text += division_event(case, system)
        if str(case["actin_mode"]) == "perinuclear":
            text += actin_renucleation_event(system, list(system["division_new"]), start=DIVISION_TIME)
    text += f"\nrun {steps} system {{ nb_frames = {frames} }}\n"
    return text


def seed_for(system: dict[str, object], case: dict[str, object], replicate: int) -> int:
    return 62000 + int(system["seed_offset"]) + int(case["index"]) * 100 + replicate


def write_run_script(case_dir: Path) -> None:
    (case_dir / "run.sh").write_text(
        dedent(
            """\
            #!/usr/bin/env bash
            set -euo pipefail
            root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../../.." && pwd)"
            "$root/sim" config.cym
            """
        ),
        encoding="utf-8",
    )
    (case_dir / "run.sh").chmod(0o755)


def write_replicates() -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for system in SYSTEMS:
        for case in CASES:
            for replicate in range(1, REPLICATES + 1):
                seed = seed_for(system, case, replicate)
                run_dir = ROOT / str(system["id"]) / str(case["name"]) / f"r{replicate:04d}"
                run_dir.mkdir(parents=True, exist_ok=True)
                (run_dir / "config.cym").write_text(
                    config_for(case, system, replicate, RUN_STEPS_5MIN, RUN_FRAMES, seed),
                    encoding="utf-8",
                )
                write_run_script(run_dir)
                rows.append(manifest_row(case, system, replicate, seed, run_dir / "config.cym"))
    return rows


def write_smoke_configs() -> None:
    smoke_case = dict(CASES[3])
    smoke_case["name"] = "00_smoke_fixed_mt_perinuclear"
    for system in SYSTEMS:
        seed = 61000 + int(system["seed_offset"])
        smoke_dir = ROOT / f"00_smoke_{system['id']}"
        smoke_dir.mkdir(parents=True, exist_ok=True)
        (smoke_dir / "config.cym").write_text(
            config_for(smoke_case, system, 0, 400, 4, seed),
            encoding="utf-8",
        )
        (smoke_dir / "run.sh").write_text(
            dedent(
                """\
                #!/usr/bin/env bash
                set -euo pipefail
                root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
                "$root/sim" config.cym
                """
            ),
            encoding="utf-8",
        )
        (smoke_dir / "run.sh").chmod(0o755)


def manifest_row(
    case: dict[str, object], system: dict[str, object], replicate: int, seed: int, config_path: Path
) -> dict[str, object]:
    box_x, box_y, box_z = system["box"]
    return {
        "system": system["id"],
        "system_label": system["label"],
        "case": case["name"],
        "case_index": case["index"],
        "description": case["description"],
        "replicate": f"r{replicate:04d}",
        "seed": seed,
        "config": config_path.relative_to(ROOT),
        "steric": case["steric"],
        "microtubules": case["microtubules"],
        "mt_mode": case["mt_mode"],
        "actin_mode": case["actin_mode"],
        "division": case["division"],
        "steps": RUN_STEPS_5MIN,
        "frames": RUN_FRAMES,
        "duration_s": RUN_STEPS_5MIN * 0.005,
        "box_x": box_x,
        "box_y": box_y,
        "box_z": box_z,
        "scale_factor": system["scale_factor"],
        "material_scale": system["material_scale"],
        "actin_total_polymer": scaled(system, BASE_ACTIN_TOTAL_POLYMER),
        "actin_max_length": ACTIN_MAX_LENGTH,
        "fixed_mt_length": system["fixed_mt_length"],
        "mt_fibers_per_site": system["mt_fibers_per_site"],
    }


def write_manifest(rows: list[dict[str, object]]) -> None:
    fieldnames = [
        "system",
        "system_label",
        "case",
        "case_index",
        "description",
        "replicate",
        "seed",
        "config",
        "steric",
        "microtubules",
        "mt_mode",
        "actin_mode",
        "division",
        "steps",
        "frames",
        "duration_s",
        "box_x",
        "box_y",
        "box_z",
        "scale_factor",
        "material_scale",
        "actin_total_polymer",
        "actin_max_length",
        "fixed_mt_length",
        "mt_fibers_per_site",
    ]
    with (ROOT / "manifest.csv").open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    ROOT.mkdir(parents=True, exist_ok=True)
    rows = write_replicates()
    write_smoke_configs()
    write_manifest(rows)
    print(f"Wrote {len(rows)} replicated configs plus {len(SYSTEMS)} smoke configs under {ROOT}")


if __name__ == "__main__":
    main()
