// Cytosim was created by Francois Nedelec. Copyright 2021 Cambridge University.
/**
 This program exports simulation objects, in a compact binary format that
 is more efficient than the text files generated by 'report'.
 The system is exported using two files:
 
 1. a file containing coordinates of the objects: 'points.float32'
    This is a binary file stored either in floating point or fixed point:
    'points.float32' : [ 4 bytes, a floating point in micrometers ]
    'points.fixed16' : [ 2 bytes, an int16 = 4096 * micrometer ],

 2. a file describing the objects: 'paths.uint32'
    This is a binary file containing uniform records consisting of:
     [4 bytes, uint32: class]
     [4 bytes, uint32: identification]
     [4 bytes, uint32: first index in 'points']
     [4 bytes, uint32: 1+last index in 'points']

 Two files are generated for each timepoint of the trajectory file.
 
 FJN, 2.06.2021
*/

#include <fstream>
#include "filepath.h"
#include "frame_reader.h"
#include "iowrapper.h"
#include "glossary.h"
#include "simul.h"


void help(std::ostream& os)
{
    os << "This program exports simulation objects, in a compact binary format that\n";
    os << "is more efficient than the text files generated by 'report'.\n";
    os << "The system is exported using two files:\n";
    
    os << "1. a file containing coordinates of the objects: 'points.float32'\n";
    os << "   This is a binary file stored either in floating point or fixed point:\n";
    os << "   'points.float32' : [ 4 bytes, a floating point in micrometers ]\n";
    os << "   'points.fixed16' : [ 4 bytes, an int32 = 4096 * micrometer ],\n";

    os << "2. a file describing the objects: 'paths.uint32'\n";
    os << "   This is a binary file containing uniform records consisting of:\n";
    os << "    [4 bytes, uint32: class]\n";
    os << "    [4 bytes, uint32: identification]\n";
    os << "    [4 bytes, uint32: first index in 'points']\n";
    os << "    [4 bytes, uint32: 1+last index in 'points']\n";

    os << "Two files are generated for each timepoint of the trajectory file.\n";
    os << "Compiled with DIM=" << DIM << "\n";
}

//------------------------------------------------------------------------------
#pragma mark - Globals

FILE* fileP = nullptr;
FILE* fileS = nullptr;

int use_fixed16 = 0;
size_t pointer = 0;
size_t overflow = 0;

//------------------------------------------------------------------------------
#pragma mark - Files

FILE * openFile(const char name[], bool binary)
{
    FILE * f = nullptr;
    
    if ( binary )
        f = fopen(name, "wb");
    else
        f = fopen(name, "w");
    if ( !f )
        std::cerr << "Error: could not create `" << name << "'\n";
    if ( f && ferror(f) )
    {
        fclose(f);
        std::cerr << "Error making `" << name << "'\n";
        f = nullptr;
    }
    return f;
}

bool openFiles(const char root[], unsigned frm)
{
    char str[256] = { 0 };
    pointer = 0;
    if ( use_fixed16 )
    {
        snprintf(str, sizeof(str), "%s%04u.fixed16", root, frm);
        fileP = openFile(str, true);
    }
    else
    {
        snprintf(str, sizeof(str), "%s%04u.float32", root, frm);
        fileP = openFile(str, true);
    }
    snprintf(str, sizeof(str), "%s%04u.uint32", root, frm);
    fileS = openFile(str, true);
    return ( fileP && fileS );
}

void closeFiles()
{
    fclose(fileP); fileP = nullptr;
    fclose(fileS); fileS = nullptr;
}

//------------------------------------------------------------------------------
#pragma mark - data write

int16_t fix(real x)
{
    constexpr real SCALE = 2048;
    long l = std::lround(SCALE*x);
    int16_t i = (int16_t)l;
    overflow += ( l != (long)i );
    //if ( l != (long)i ) fprintf(stderr, "fixed16 overflow %f %li\n", x, l);
    return i;
}

void writeVector16(Vector3 const& pos)
{
#if ( DIM == 3 )
    int16_t vec[3] = { fix(pos.XX), fix(pos.YY), fix(pos.ZZ) };
#else
    int16_t vec[3] = { fix(pos.XX), fix(pos.YY), 0 };
#endif
    fwrite(vec, DIM, sizeof(int16_t), fileP);
    pointer += DIM;
}

void writeVector32(Vector3 const& pos)
{
    float vec[3] = { 0 };
    pos.store(vec);
    fwrite(vec, DIM, sizeof(float), fileP);
    pointer += DIM;
}

void writeObject(uint32_t a, uint32_t b, uint32_t c, uint32_t d)
{
    fwrite(&a, 1, 4, fileS);
    fwrite(&b, 1, 4, fileS);
    fwrite(&c, 1, 4, fileS);
    fwrite(&d, 1, 4, fileS);
}

//------------------------------------------------------------------------------
#pragma mark -

void writeFibers32(FiberSet const& fibers)
{
    // process fibers in the natural order:
    for ( Fiber const* fib = fibers.firstID(); fib; fib = fibers.nextID(fib) )
    {
        size_t start = pointer;
        for ( size_t i = 0; i < fib->nbPoints(); ++i )
            writeVector32(fib->posPoint(i));
        
        writeObject(fib->prop->number(), fib->identity(), start, pointer);
    }
}

void writeFibers16(FiberSet const& fibers)
{
    overflow = 0;
    
    // process fibers in the natural order:
    for ( Fiber const* fib = fibers.firstID(); fib; fib = fibers.nextID(fib) )
    {
        size_t start = pointer;
        for ( size_t i = 0; i < fib->nbPoints(); ++i )
            writeVector16(fib->posPoint(i));
        
        writeObject(fib->prop->number(), fib->identity(), start, pointer);
    }
    
    if ( overflow )
        fprintf(stderr, "Warning: fixed16 data format overflowed %lu times\n", overflow);
}

//------------------------------------------------------------------------------
#pragma mark -

int main(int argc, char* argv[])
{
    if ( argc < 2 || strstr(argv[1], "help") )
    {
        help(std::cout);
        return EXIT_SUCCESS;
    }
    
    std::string what = argv[1];
    if ( what != "fiber" )
    {
        help(std::cout);
        return EXIT_SUCCESS;
    }

    Glossary arg;
    if ( arg.read_strings(argc-2, argv+2) )
        return EXIT_FAILURE;
    
    if ( arg.has_key("directory") )
        FilePath::change_dir(arg.value("directory"));

    arg.set(use_fixed16, "fixed");
    std::string input = TRAJECTORY;
    arg.set(input, ".cmo") || arg.set(input, "input");

    Simul simul;
    FrameReader reader;
    reader.openFile(input);
    
    if ( !reader.good() )
    {
        fprintf(stderr, "could not open input file\n");
        return EXIT_FAILURE;
    }
    
    try
    {
        unsigned frm = 0;
        simul.loadProperties();
        // process all frames of the trajectory:
        while ( 0 == reader.loadNextFrame(simul) )
        {
            if ( openFiles(what.c_str(), frm) )
            {
                if ( use_fixed16 )
                    writeFibers16(simul.fibers);
                else
                    writeFibers32(simul.fibers);
                closeFiles();
            }
            ++frm;
        }
    }
    catch( Exception & e )
    {
        std::cerr << e.brief() << '\n';
        return EXIT_FAILURE;
    }
}
